### ISSUE TITLE
Custom models walk-through link in Readme refers to content that has been removed

### ISSUE THREAD

**Issue by dinoboy197** [datarobot/datarobot-user-models#535]
The custom models walk-through link in the README.md file (https://community.datarobot.com/t5/knowledge-base/working-with-custom-models/ta-p/6082) refers to a page that is removed content. The moderator of that page says that the content has moved elsewhere, but does not say where the content has moved _to_.

It would be nice if the link in the README file were updated to point to the new content, wherever that is.

**Comment by ToonWeyens** [comment]
+1

**Comment by aslisabanci** [comment]
Hey @dinoboy197 & @ToonWeyens, I updated the README to fix the issue, thanks for bringing it up.
