### ISSUE TITLE
broken link in readme.md

### ISSUE THREAD

**Issue by ToonWeyens** [datarobot/datarobot-user-models#654]
https://docs.datarobot.com/en/docs/release/public-preview/automl-preview/cml/cml-quickstart.html is referred under custom tasks.

**Comment by ToonWeyens** [comment]
And so is https://docs.datarobot.com/en/docs/release/public-preview/automl-preview/cml/index.html

**Comment by c-h-russell-walker** [comment]
Hi, thanks for creating this issue - I can see that these links are no longer in our README so closing this issue.
