### ISSUE TITLE
Numpy version mismatch

### ISSUE THREAD

**Issue by jakemsnyder** [datarobot/datarobot-user-models#72]
Following the instructions in the readme, the virtual environment I create installs numpy==1.19.0. But the public sklearn environments in staging and prod use numpy==1.16.4. This causes problems when I upload my model because it will pass drum testing locally, then fail in DataRobot (because it will not be able to load the pickle file). Can we update the [requirements file](https://github.com/datarobot/datarobot-user-models/blob/master/requirements.txt) to specify the appropriate package versions?

**Comment by yakov-g** [comment]
Hey @jakemsnyder, which instructions do you follow?

**Comment by jakemsnyder** [comment]
Instructions after Running examples header here: https://pypi.org/project/datarobot-drum/

**Comment by yakov-g** [comment]
We are updating this right now.
Consider those docs obsolete for a couple of days.
Please use this: https://github.com/datarobot/datarobot-user-models/tree/yakov/docs/custom_model_runner
Which will lead you to: https://github.com/datarobot/datarobot-user-models/
